### ISSUE TITLE
"Please refer to the docs for using encryption" message on calling rc.request_pin_code()

### ISSUE THREAD

**Issue by jontywigster** [florianholzapfel/panasonic-viera#11]
Hi, 

I'm running the sample code -

```
import panasonic_viera
rc = panasonic_viera.RemoteControl("10.3.1.20")
# Make the TV display a pairing pin code
rc.request_pin_code()
```

When rc.request_pin_code() is called, init.py gets only as far as -

```
elif self._type == TV_TYPE_ENCRYPTED:
                raise EncryptionRequired("Please refer to the docs for using encryption")
```

My TV is a TX-49GXW904. It's a 2019 model and does indeed need a pin.

Could someone please point me in the direction of those docs, or any hint at how to get further would be great. I'm sorry for the noob question. 

Oops, I forgot to say - I've tried in both Python 2.7 and 3.7. Both give the same result.

**Comment by Flyingfufu** [comment]
Hi,

I also get issue, but following fault message when running my pin code request message:

Traceback (most recent call last):
  File "pin.py", line 4, in <module>
    rc.request_pin_code()
  File "/opt/QPython2/lib/python2.7/site-packages/panasonic_viera/__init__.py", line 310, in request_pin_code
    res = self.soap_request(URL_CONTROL_NRC, URN_REMOTE_CONTROL, 'X_DisplayPinCode', params, body_elem="u")
  File "/opt/QPython2/lib/python2.7/site-packages/panasonic_viera/__init__.py", line 211, in soap_request
    raise EncryptionRequired("Please refer to the docs for using encryption")
panasonic_viera.EncryptionRequired: Please refer to the docs for using encryption

Any help will be welcome too.

**Comment by msbc42** [comment]
Same issue for me on macOS python 2.7

**Comment by dawiinci** [comment]
Not working for me as well on macOS, any plans to fix this or is this plugin broken?

   

>   File "/Library/Python/2.7/site-packages/panasonic_viera/__init__.py", line 310, in request_pin_code
>        res = self.soap_request(URL_CONTROL_NRC, URN_REMOTE_CONTROL, 'X_DisplayPinCode', params, body_elem="u")
>      File "/Library/Python/2.7/site-packages/panasonic_viera/__init__.py", line 211, in soap_request
>        raise EncryptionRequired("Please refer to the docs for using encryption")
> EncryptionRequired: Please refer to the docs for using encryption

**Comment by dawiinci** [comment]
Is it recommended to install pycryptodome? Because at first I got this error:

> ImportError: No module named Crypto.Cipher   

After installation I get the error "Please refer to the docs for using encryption".

I can add the remote App to the TV by adding the PIN code, so it is working.

Please anyone help us to fix this. I don't want to waste energy until the tv switches off automatically in case I forget the remote.

**Comment by ngws** [comment]
This was my mistake, soap_request() was incorrectly trying to enforce encryption on X_DisplayPinCode requests. I have created PR https://github.com/florianholzapfel/panasonic-viera/pull/14 which should fix this.

**Comment by dawiinci** [comment]
Thanks for the quick fix. I can now get a PIN, but after calling rc.authorize_pin_code(pincode=pin)
it fails again with the same message.

` File "/Library/Python/2.7/site-packages/panasonic_viera/__init__.py", line 349, in authorize_pin_code
       res = self.soap_request(URL_CONTROL_NRC, URN_REMOTE_CONTROL, 'X_RequestAuth', params, body_elem="u")
     File "/Library/Python/2.7/site-packages/panasonic_viera/__init__.py", line 211, in soap_request
       raise EncryptionRequired("Please refer to the docs for using encryption")
EncryptionRequired: Please refer to the docs for using encryption
`

**Comment by ngws** [comment]
PR https://github.com/florianholzapfel/panasonic-viera/pull/15 will fully fix this.

**Comment by ErwinKaloschke** [comment]
Hi,
when I use your example to send epg key I get this message:

File "send_epg.py", line 3, in <module> rc.send_key(panasonic_viera.Keys.epg)
File "C:\Python27\lib\panasonic_viera\__init__.py", line 526, in send_key "X_SendKey', params)
File "C:\Python27\lib\panasonic_viera\__init__.py", line 211, in soap_request raise EncryptionRequired("Please refer ...")  panasonic_viera.EncryptionRequired: Please refer ...

**Comment by jontywigster** [comment]
Hello, 

Many thanks again for taking a look at this. I've tried again and am stuck at request_pin_code for a different reason - my TV is sending back 403 Forbidden. 

Looking at the traffic, GETting /nrc/sdd_0.xml does return X_DisplayPinCode in the actionList. The next thing that seems to happen is a post to /nrc/control_0, which contains the X_DisplayPinCode request. To this request, the TV says no, i.e. 403 Forbidden.

As far as I can tell, all options on the TV to allow control from apps etc. are enabled. In any case, this seems to be a problem with my TV rather than code so I'm happy to close this issue, if this is appropriate. I guess this would mean that @ErwinKaloschke - you probably need to open a separate issue for your problem with sending the epg key as I don't think this is related to why I originally opened this issue. Sorry!
