### ISSUE TITLE
Add Launching Apps

### ISSUE THREAD

**Issue by bfayers** [florianholzapfel/panasonic-viera#12]
In the Panasonic TV Control 2 app on android you can launch apps on the TV (Amazon Prime, Plex, ETC).

I have successfully captured the request to get the list of apps from the TV and the request to start a given app on the TV. I have attached the files. Hopefully I can wrap my head around the library and put in a PR, or someone else may be able to take advantage of the info.

[GetAppList.txt](https://github.com/florianholzapfel/panasonic-viera/files/3496628/GetAppList.txt)
[LaunchApp.txt](https://github.com/florianholzapfel/panasonic-viera/files/3496629/LaunchApp.txt)

**Comment by bfayers** [comment]
If you take the string enclosed in `<X_AppList></X_AppList>` and do the following to it you end up with a dictionary of name to product id.



```
TVApps =<X_AppList value here>
import re

apps = TVApps.split("vc_app")[1:]

app_list = {}
for app in apps:
    prod_id = re.search('(?<=product_id\=)(.*?)(?=&apos;)', app).group(0)
    name = re.search('(?<='+prod_id+'&apos;)(.*?)(?=&apos;)', app).group(0)
    app_list[name] = prod_id
```

This is probably by no means a good way to parse this, it is just a way to parse it.

**Comment by nodecentral** [comment]
Hi @bfayers - have you managed to make any more progress on this?

**Comment by bfayers** [comment]
@nodecentral Unfortunately not, I haven't had time to wrap my head around the library enough.

The packet captures I dumped should be enough for anyone to work out how to add app launching though. I'll try and get time to look into it soon.
