### ISSUE TITLE
Lua - Controlling Panasonic TV

### ISSUE THREAD

**Issue by nodecentral** [florianholzapfel/panasonic-viera#17]
Hi,

Looking at all the information on here, I’m keen to make this work with my Vera Home automation controller, which uses The LUA language - I found this on their community site for a [Sony TV](https://community.getvera.com/t/sony-tv-rest-api/191302), and it makes me wonder if something similar would work for my Panasonic OLED

```
local SONY_IP = "xxx.xxx.xxx.xxx" --luup.devices[lul_device].ip
local AUTH_CODE = "password" --luup.devices[lul_device].authkey
function SetPower(Status)
    local SONY_URL = "http://"..SONY_IP.."/sony/system"
    local http = require("socket.http")
    local ltn12 = require("ltn12")
    local respBody = {}
    local REQUEST = '{"method":"setPowerStatus","version":"1.0","params":[{"status":'..Status..'}],"id":102}'
    rBody, rCode, rHeaders, rStatus = http.request(
      {
            method = "POST",
            url = SONY_URL,
            headers = {
                ["User-Agent"] = "curl/7.38.0",
                ["Host"] = SONY_IP,
                ["Accept"] = "*/*",
                ["X-Auth-PSK"] = AUTH_CODE,
                ["Content-Type"] = "application/json",
                ["Content-Length"] = tostring(#REQUEST),
            },
            source = ltn12.source.string(REQUEST),
            sink = ltn12.sink.table(respBody),
            redirect = false
        }
    )
    luup.log("http response - code ["..(rCode or "NIL").."] html ["..(table.concat(respBody,"") or "NIL").."]")
end

SetPower("false")
```

`

**Comment by florianholzapfel** [comment]
have a look at the following code: https://forum.logicmachine.net/showthread.php?tid=232

this will probably work for you.

**Comment by nodecentral** [comment]
Unfortunately the code on the logicmachine forum leverages elements of what seems to be a proprietary Lua library/modules, so i’m having to try and find alternatives to allow me to pair and then control my Tv using Lua ‘out of the box’, making it much more transportable.

I’ve started a thread on the Vera Home Control forum, which is a Home Automation controller I use that leverage the Lua language too. - https://community.getvera.com/t/panasonic-tv-pincode-and-encryption-support/216268/2

if anyone is able to assist - I would really appreciate the help so there is a Lua version too available for people to use.
