### ISSUE TITLE
Source code questions

### ISSUE THREAD

**Issue by GreenSnakeLinux** [florianholzapfel/panasonic-viera#18]
Hello,

In __init__.py line 229 it seems that it is missing a "

I trying to port the code on Android java
But I have a code error 400: Bad request

Is there something to turn on in the TV setting ? (Model: Panasonic 58DX800)

In the header request, is the order important ?
I found some others code with different order, and different header values:
In the 'Host' header value, there is no PORT number
In the 'Content-Type', there is only "text/xml"

thanks in advance

**Comment by florianholzapfel** [comment]
as far as i remeber, there is an option in the tv settings to turn on the remote control via app.

**Comment by GreenSnakeLinux** [comment]
Here is the option path on the TV:
Network > TV Remote App Settings > TV Remote
See configuration tab on Panasonic web site:
https://av.jpn.support.panasonic.com/support/global/cs/tv/vremote2/android/index.html

Anyway I still have the error 400
I made a github of the project for Android, if someone can test it and found the solution:
https://github.com/GreenSnakeLinux/Panasonic
The apk build is present too if you cannot compile it and want to test only.
thanks
