### ISSUE TITLE
HomeAssistant media_player.turn_off is a power toggle instead power off

### ISSUE THREAD

**Issue by outrun0506** [florianholzapfel/panasonic-viera#2]
Hi,

i just open an issue in the HomeAssistant Repro an the guys send me to you.

Heres my issue in Homeassistant:

https://github.com/home-assistant/home-assistant/issues/5157

Any chance to fix this?

**Comment by florianholzapfel** [comment]
this needs to be fixed in the home assistant component.

this library does not manage the current state of the tv. it is just used to send commands to the tv. the button ```NRC_POWER-ONOFF``` directly corresponds to the power button on your tv remote: it is a toggle button. the methods name (```turn_off```) is very misleading here.

**Comment by outrun0506** [comment]
Thanks a lot for help
