### ISSUE TITLE
GZ950 series not working

### ISSUE THREAD

**Issue by Depechie** [florianholzapfel/panasonic-viera#27]
Guess a bit the same as the other issues... but still wanted to log it.
So a new GZ950 OLED does get media player status info, but the commands to turn on or off or volume is not working.
Running latest 0.102.3 Home Assistant.
Tried with mac address too and no luck.

The official Panasonic remote app for iPhone does work, but first time connecting you need to pair it with a 4 number pin.
Can we do something similar in Home Assistant?

**Comment by Depechie** [comment]
After some tweaks in the Panasonic menu settings off the TV, when enabling Wake on Lan setting, I can turn on the TV with this library.
Also volume controlling is working, only turning off gives a http 500 error.

**Comment by anoko3000** [comment]
Hello @Depechie can you write the code to enter the verification code to the TV and how to register the ID?

**Comment by anoko3000** [comment]
I've got to send a verification code to TV and it showed in to it. But no way to send the pin code again to the tv.

**Comment by Depechie** [comment]
The new add-on for home assistant allows this flow of pin verification. I’m using that now.
