### ISSUE TITLE
Die neue PIN Eingabe als PHP Skript

### ISSUE THREAD

**Issue by Steg71** [florianholzapfel/panasonic-viera#29]
Hallo Florian,
wäre es dir möglich dieses Phyton Skript auch in PHP zu schreiben? Ich nutze IP Symcon das nur PHP unterstützt. Es gibt dafür ein passendes Modul aber ohne diese neue Funktion der neuen Geräte.

Wäre schön von dir zu hören.

Viele Grüße
Stefan

**Comment by florianholzapfel** [comment]
Hallo Stefan,
danke für Deine Nachricht. Leider habe ich zu wenig Erfahrung mit PHP und IP Symcom um das Modul zu portieren zu können.

Grüße
Florian

**Comment by Steg71** [comment]
Hallo Florian,
trotzdem Danke für deine schnelle Nachricht. Schade, dann muss ich mal schauen wie ich das hinbekommen kann. Im Symcon Forum hat jemand schon mal dein Python Skript per PHP aufgerufen mit IPS_Execute(). Leider ist für mich PHP auch ein Buch mit 7 Siegel.
LG
Stefan
