### ISSUE TITLE
0.4.0 breaks functionality

### ISSUE THREAD

**Issue by dawiinci** [florianholzapfel/panasonic-viera#38]
```
   Script Error                    Panasonic Aus.py: invalid syntax
   Script Error                    around line 477 - ""HOST": f"{self._host}:{self._port}","
```

If I revert back to 0.3.6 it works again. I use the script in Indigo 7.4.

**Comment by florianholzapfel** [comment]
do you more information on this issue? what is software is indigo 7.4? how does it make use of this python module? where does the file `Panasonic Aus.py` come from? can i have a look at it?

**Comment by boisei0** [comment]
You're right, it's f-strings added in the PR that got merged in. Which Python version are you running? As far as I know Indigo uses the builtin Python on Mac systems: https://forums.indigodomo.com/viewtopic.php?f=75&t=22942
F-strings were added to Python 3.6. Any version older than that won't be able to run the code.

**Comment by dawiinci** [comment]
Yes, you are right. Indigo uses Python 2, I can't change that to 3.

`app_id = str(indigo.variables[1578171917].value)
encryption_key = str(indigo.variables[490143362].value)
ip = str(indigo.variables[859126059].value)
host= 55000

import panasonic_viera
rc = panasonic_viera.RemoteControl(ip, host, app_id, encryption_key)

rc.turn_off()`
