### ISSUE TITLE
Cross network support - question

### ISSUE THREAD

**Issue by psyciknz** [florianholzapfel/panasonic-viera#49]
Hi.  I managed to find this project after initially trying the home assistant integration and finding it didn't work for me.

Are you aware of anything in your travels with the panasonic tvs that restricts access based on the tv and calling device being in the same network?

I've managed to hack together a small container I can put in the same vlan as my tv and get it to respond.  Just curious is anyone else had seen this as my only solution at the moment might be to implement some sort of mqtt bridge and control the tv from home assistant that way.

**Comment by nodecentral** [comment]
I think I experienced something similar with the Viera Homebridge plugin, that would only work if both were on the same subnet/network.

**Comment by psyciknz** [comment]
Thanks .  That’s is good to understand it is not my setup.  Ok.  I might use this project and implement an mqtt bridges. So it is accessible by anything

**Comment by nodecentral** [comment]
Hi @psyciknz , I’d be interested to follow your progress if you share it somewhere.

**Comment by psyciknz** [comment]
Putting it in here: https://github.com/psyciknz/vieramqtt
I haven't tried running anything yet.  Was just working on the authorisation flow.   So at the moment will post to status that it wants a pin to viera/status, then you have to send that back to a topic of viera/pin.  

Then I can work out getting some commands to the tv.
