### ISSUE TITLE
Does this really work?

### ISSUE THREAD

**Issue by khara02** [florianholzapfel/panasonic-viera#53]
https://github.com/florianholzapfel/panasonic-viera/issues/48
It's said HDMI input functions are added but It doesn't seems so?

**Comment by florianholzapfel** [comment]
The functions have been added to the code, but there has not been a release on PyPI yet.

**Comment by khara02** [comment]
How do I make it work?
Overwrite certain files?

**Comment by florianholzapfel** [comment]
You can use the master branch. Or you could use the `send_key` function with the key code for the HDMI key (e.g. `NRC_HDMI1-ONOFF`).

**Comment by khara02** [comment]
Could you share when these might be available on PyPI?

Thank you for your efforts with this project.

**Comment by florianholzapfel** [comment]
I have just released version 0.4.2 on PyPI

**Comment by khara02** [comment]
Thank you for your prompt response!
