### ISSUE TITLE
How to intsall on arch linux?

### ISSUE THREAD

**Issue by HoerMirAuf** [florianholzapfel/panasonic-viera#54]
Is there a guide how to install it on arch linux?

**Comment by florianholzapfel** [comment]
arch linux expects you to install either packages that are packaged with pacman or to use a virtual environment for everything else. Please have a look at https://wiki.archlinux.org/title/Python/Virtual_environment for instructions on how to create a virtual envronment. You should be able to use pip inside the venv to install this package there.
