### ISSUE TITLE
New feature: Send notification

### ISSUE THREAD

**Issue by titilambert** [florianholzapfel/panasonic-viera#6]
Hello, I want to send a notification to my Panasonic Viera.
I can develop it in python, but I don't know where I can found some information/API endpoint to do that.
Do you have any idea how to do that ?

Thanks !

**Comment by dgomes** [comment]
There isn't any public API AFAIK. But wireshark is your pall 👍

**Comment by florianholzapfel** [comment]
Unfortunately, there is no public API. Wireshark will probably be your only solution to reverse engineer the endpoint.

**Comment by nodecentral** [comment]
Messaging via HDMI CEC could be an option..

http://events17.linuxfoundation.org/sites/events/files/slides/cec-elce2016.pdf
